Repository dohyeonYoon/Deep-Learning-Paper-Review, pull requests merged in 2024-12, with the labels that each got.

#17 Docs: Add paper review on etc, close #16
  README.md
Labels: Multi-modal, CG

#19 Docs: Add paper review on etc, close #18
  README.md
Labels: CV

#21 Docs: Add paper review on Computer Graphics, close #20
  README.md
Labels: CG
